---
title: "Project Topic 3 Team 4"
author: "Khalida Dushimova, Madleen Piegsa, Greata Karathanos und Richard Langi Efraim"
date: "4/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Description of dataset (Raw data)



```{r 1.1 loading data}
#loading "RDeeP_A549_NS.csv" into Data.raw dataframe
#MS_Table <- read.table("D:\Uni\4. Semester\Data Analysis\RDeeP_A549_NS.csv", header=TRUE, row.names=1, sep = ";")
Data.raw <- read.table("D:\\Uni\\4. Semester\\Data Analysis\\RDeeP_A549_NS.csv", header=TRUE, row.names=1, sep = ";")


#creating a copy of Data.raw and saving it as Data.copy
Data.copy = Data.raw

```

```{r}
# Data Normalization

#Define Min-Max normalization function
min_max_norm <- function(x) {
    (x - min(x)) / (max(x) - min(x))
  }

#apply Min-Max normalization to first four columns in iris dataset
Data.norm <- as.data.frame(lapply(Data.copy[1:150], min_max_norm))

```

```{r 1.2 Raw data reorganization}


```



```{r}
# RNA associates with proteins to form RNA-Protein complexes that play key regulatory roles in cellular processes --> RNA metabolism and the regulation of gene expression 

# concept of RNA dependence (R-DeeP) describes proteins and protein complexes whose interactions are directly or indirectly dependent on the presence of RNA 



# aim: identify RNA-dependent proteins from the position of the proteins in an untreated cell lysate as t
```

## 1. Evaluation of the reproducibility of the experiments 


## 2. Normalization

## 3. Peaks identification

## 4. Fit of the protein profiles

## 5. 




